- type: fieldset
  title: Home
  items:
    - key: title
      fieldHtmlClass: input-xxlarge
    - key: description
      type: textarea
- type: fieldset
  title: Advanced Settings
  expandable: true
  items:
    - key: colour
      type: color
    - key: meta-description
      fieldHtmlClass: input-xxlarge
- type: submit
  title: Update